# -*- coding: utf-8 -*-
"""Feature_Engineering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DxKnQA6ZmW2hAMq4CA2qntRXKt0V2Bsb
"""

from sklearn import preprocessing
from sklearn import metrics
import numpy as np
import pandas as pd
import seaborn as sns
from matplotlib import pyplot as plt
import datetime as dt

s_date=pd.date_range('2020-03-16','2020-08-03',freq='24H').to_frame()

print(s_date)

df=pd.read_csv("/content/wineQualityReds.csv")
df_obj=preprocessing.PolynomialFeatures(degree=2,interaction_only=False,include_bias=False)
df_obj.fit(df)

df_poly=df_obj.transform(df)

print(df_poly)

pp=df_poly.shape[1] #0 for the row #1 for the Columns
df_modified=pd.DataFrame(df_poly,columns=[f"poly_feature_{i}" for i in range(1,pp+1)])

df_modified.tail()
#New Fucing Feature
#Polynomial Features

def datefeatures(df):
  df.loc[:,'year']=df['date'].dt.year
  df.loc[:,'weekofyear']=df['date'].dt.weekofyear
  df.loc[:,'month']=df['date'].dt.month
  df.loc[:,'dayoftheweek']=df['date'].dt.dayoftheweek
  df.loc[:,'weekend']=(df['date'].dt.dayoftheweek >= 5).astype(bool)

  agg=dict()
  agg['month']=['nunique','mean']
  agg['weekoftheyear']=['nunique','mean','min','max']
  agg['year']=['nunique','mean']

  df_modified=df.groupby('ID').agg(agg).reset_index()
  return df_modified

